{"name": "test_DELETE_ID_Pet", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise", "trace": "self = <tests.test_PetDemoProject_api.Test_Pets object at 0x0000022306531C50>\n\n    @allure.description(\"Удаление животного по ID\")\n    def test_DELETE_ID_Pet(self):\n>       Pet_Demo_api.DELETE_Pet()\n\ntests\\test_PetDemoProject_api.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @staticmethod\n    def DELETE_Pet():\n        if Pet_Demo_api.ID is None:\n            print(\"ID не установлен\")\n>           raise  # указываем об ошибке\nE           RuntimeError: No active exception to reraise\n\nutils\\API_Pets.py:135: RuntimeError"}, "description": "Удаление животного по ID", "attachments": [{"name": "stdout", "source": "e69833d8-a5ff-4ffe-8b48-3e31f520964a-attachment.txt", "type": "text/plain"}], "start": 1696768305158, "stop": 1696768305159, "uuid": "825f817b-e81f-4613-af2f-1b858cc4f286", "historyId": "da2dedd4e5947daa28cf41d872c6d5ce", "testCaseId": "6f5600ec4d86cab587687736c5505976", "fullName": "tests.test_PetDemoProject_api.Test_Pets#test_DELETE_ID_Pet", "labels": [{"name": "epic", "value": "Управление животными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_PetDemoProject_api"}, {"name": "subSuite", "value": "Test_Pets"}, {"name": "host", "value": "LAPTOP-DQ0BFIQ6"}, {"name": "thread", "value": "12036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_PetDemoProject_api"}]}